version: '3.8'

services:
  frontBack:
    image: mysute
    container_name: mysute-web-server
    ports:
      - "80:80"
    volumes:
      # Монтируем все сайты из папки sites
      - ./php/:/var/www/html/mysute/
      # Монтируем кастомный конфиг
      - ./nginxConf/nginx.conf:/etc/nginx/conf.d/default.conf
      # Монтируем конфиг fastcgi
      - ./php/php-fastcgi.conf:/etc/php/8.4/fpm/php-fpm.conf
    restart: unless-stopped

  db:
    image: mysql
    container_name: db-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # Монтируем все сайты из папки sites
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql
      # Монтируем кастомный конфиг
      - ./config/:/etc/nginx/conf.d/
    restart: unless-stopped

networks:
  web-network:
    driver: bridge