server {
	listen 80; # v4 протокол

	root /var/www/html/droll; #папка с сайтами

	index index.html index.htm index.nginx-debian.html; #Названия которые nginx пытается найти при запросе

	server_name droll.test; # "_" - отвечает на все запросы

	location / {
		try_files $uri $uri/ =404; # Набор правил
	}
}